apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: yelp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        uploads-group: shared
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  uploads-group: shared
              topologyKey: kubernetes.io/hostname
      containers:
        - name: user-service
          image: REPLACE_ECR_URL/yelp/user-service:latest
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: yelp-config
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: yelp-secret
                  key: SECRET_KEY
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: yelp
spec:
  selector:
    app: user-service
  ports:
    - port: 8001
      targetPort: 8001
